config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'articles#index'

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 20 }, uniqueness: true
  validates :body, presence: true, length: { minimum: 50 }

  scope :sorted, -> { order(published_at: :desc )}
  scope :draft, -> { where(published_at: nil) }
  scope :published, -> { where('published_at <= ?', Time.current) }
  scope :schedule, -> { where('published_at > ?', Time.current) }

  def draft?
    published_at.nil?
  end

  def published?
    published_at.present? && published_at <= Time.current
  end

  def scheduled?
    published_at.present? && published_at > Time.current
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_article, only: %i[show edit update destroy]
  def index
    @articles = user_signed_in? ? Article.sorted : Article.published.sorted
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    redirect_to root_path
  end

  private

  def set_article
    if user_signed_in?
      @article = Article.find(params[:id])
    else
      @article = Article.find(params[:id])
    end
  end

  def article_params
    params.require(:article).permit(:title, :body, :published_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |f| %>

  <div>
    <%= f.label :title %>
    <%= f.text_area :title %>
      <% article.errors.full_messages_for(:title).each do |error| %>
        <div><%= error %></div>
      <% end %>
  </div>

  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
     <% article.errors.full_messages_for(:body).each do |error| %>
        <div><%= error %></div>
      <% end %>
  </div>

  <div>
    <%= f.label :published_at %>
    <%= f.datetime_select :published_at, include_blank: true %>
  </div>


    <%= f.submit %>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit this post</h1>

<%= render "form", article: @article %>

</br>
<%= link_to "undone", article_path(@article) %>
<%= button_to "Delete Article", @article, method: :delete, data: {turbo_confirm: "Are you sure you want this Artcile deleted?"} %>

app/views/articles/index.html.erb
<%= link_to "new article", new_article_path if user_signed_in? %>

<h1>My new blogs</h1>
<h2>New in Tech</h2>

<% @articles.each do |article| %>
  <div class="px-4 py-2 my-2 border border-slate-500 rounded-xl">

    <h3><%= link_to article.title, article %></h3>
    <p><%= article.body %></p>

    <% if article.draft? %>
      <div class="bg-red-400 text-white rounded-full py-2 px-1 text-xs w-20 text-center shadow-xl">
        DRAFT
      </div>
    <% elsif article.scheduled? %>
      <p class="text-red-500">this article gonna be available in <%= article.published_at %></p>
    <% end %>
  </div>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

<h4><%= link_to 'Come Back', articles_path %></h4>

app/views/articles/show.html.erb
<h4><%= link_to 'Come back', articles_path %></h4>

<h1><%= @article.title %></h1>
<p><%= @article.body %></p>


<h3><%= link_to "Edit", edit_article_path(@article) if user_signed_in? %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PatrickBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="prose mx-auto bg-slate-300">

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if user_signed_in? %>
      <%# <%= link_to "Profile", edit_user_registration_path %>
      <%= button_to "Logout", destroy_user_session_path, method: :delete %>
      <%# <% else %>
      <%# <%= link_to "login", new_user_session_path %>
      <%# <%= link_to "signUp", new_user_registration_path %>
    <% end %>

    <%= yield %>
  </body>
</html>